In [20]:
#파일 입출력
f4 = open("./text2.txt","r",encoding="utf-8")
print(f4.read())

f4.seek(0)                      #seek(위치): 해당하는 위치로 커서 이동(한글은 2의 배수), seek(0)을 이용하면 제일 앞으로 이동
print(f4.tell())

context = f4.readlines()        #readlines(): 파일의 모든 줄을 읽고, 각각의 줄을 요소로 갖는 리스트를 반환
print(context)

f4.close


hello
안녕
반가워
난, 코딩온이야


<function TextIOWrapper.close()>

In [18]:
#with open을 하면 .close를 사용할 필요X
#with open("example.txt","a") as file:         # a : 파일의 뒷부분에 데이터를 추가
#    file.write("hi")                          # with open("example.txt","a") as file = file이라는 객체에 데이터를 추가
                                               # file이라는 객체에 .write를 사용해서 hi를 쓴다. (결과물:hi 또는 hihihi)
                                                
#with open("example.txt","a") as file:         
#    file.write("\nhi")                        #\n을 써줌으로써 쓸때마다 엔터가 된다.
    
with open("example.txt","r") as file:          #open("example.txt","r") as file = file이라는 객체에 example파일을 읽기 위해서 연다
    print(file.read())


hihihi
hihi
hihi
hihi
hihi
hihi
hihi
hihi
hi


In [19]:
#이미 존재하는 파일이라면 건드는게 무서워, 새로운 파일로 만들고 싶어
with open("newtext2.txt","x") as file:          # x : 새로운 파일을 생성할때 사용 ("만들 파일 이름","x")
    file.write("this is a new file")

In [49]:
info = []

for _ in range(3):
    text = input("아이디 비밀번호 ex)유즈 123")
    info.append(text)

with open("./text.txt", "a") as f:
    for line in info:
        f.write(line + "\n")

# 미리 한줄 읽기
#with open("./text.txt", "r") as f: 
#    line = f.readline()
#    while line:
        print(line.strip()) # 개행문자 제거하여 출력
#        line = f.readline()

유저1 123
유저2 456
유저3 789


In [13]:

with open("text.txt", "r") as file:
    #lines = file.readlines()                 #print 하면 => ['유저1 123\n', '유저2 456\n', '유저3 789\n']
    line = file.readline()                  #print 하면 => 유저1 123
    #print(lines)
    
    for line in line:
        #print(line)                    #\n이 자동으로 추가되어있다 그래서 strip()으로 잘라서 라인을 만들어 준다.
        print(line.rstrip("\n"))

유
저
1
 
1
2
3



In [46]:
#실습1
PW = []

for _ in range(3):
    user_pw = input("비밀번호 입력")        #비밀번호 입력 받아서 추가하기
    PW.append(user_pw)

with open("member.txt","a") as PWinfo:     #입력 받은 비밀번호를 파일에 추가하기
    for line in PW:
        PWinfo.write(line + "\n")

with open("member.txt","r") as PWinfo:     #파일을 읽는다
    print(PWinfo.read())

1234
1234
1234



In [24]:
#실습 2
#아이디 비밀번호 입력 받아서 출력하기
#readline()해서 나온 값과 입력한 값 일치시키기?
ID_input = input("이름을 입력하세요")

with open("member.txt","r", encoding="utf-8") as login:
    file_name = login.readlines()                            #홍길동
    #print(file_name)

file_name = []    
    
if ID_input in file_name:
    print("로그인 성공")
else:
    print("다시 입력하세요")
#if file_name == ID_input:
#    print("로그인 성공")
#else:
#    print("다시 입력하세요")

['홍길동\n', '1234']
다시 입력하세요


In [25]:
try:
    print(3/0)
except:
    print("error")    

error


In [10]:
try:
    num = int(input('숫자 입력:'))
    print(f"정수 입력 성공:{num}")
except:
    print("정수가 아님! 정수를 입력해 주세요!")
#if int() == num:
#    print(f"정수 입력 성공:{num}")

정수가 아님! 정수를 입력해 주세요!


In [18]:
# 데이터분석 실습 1
import numpy as np
x = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
print(x)
x = np.array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])
print(x)
x = np.full((1,10), 0)
print(x)
print(np.arange(0,31))
print(np.random.randint(0,100, size=(2,2)))
print(np.random.rand(2,4))

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]
[[0 0 0 0 0 0 0 0 0 0]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
[[94 39]
 [38 12]]
[[0.29073238 0.16151826 0.63048107 0.57418631]
 [0.26435199 0.25416237 0.56726727 0.85681899]]


In [80]:
#데이터분석 실습2

import numpy as np
x = np.arange(35,75)
#print(x)
print(x.reshape(10,4))
y = x.reshape(10,4)
#실습 7번 역순으로 출력하기
#print(y[::-1])
#실습 8번 슬라이싱
#print(y[1:9,2:])
#실습 9번 슬라이싱
print(y[:,3]) # 9번 정답
print(y[:,3:]) # 9-1번 정답
a = y[:,3:]


[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]
[38 42 46 50 54 58 62 66 70 74]
[[38]
 [42]
 [46]
 [50]
 [54]
 [58]
 [62]
 [66]
 [70]
 [74]]


In [79]:
import numpy as np
#numpy2 실습
A = [1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100]

New_A=np.unique(A)
print(New_A)

print(np.max(New_A))
print(np.min(New_A))
print(np.mean(New_A))
print(np.sum(New_A))
print(np.median(A))


[  1   2   3   4   5   7   8   9  10  11  24 100]
100
1
15.333333333333334
184
5.0
